language: python
dist: xenial

services:
- docker

stages:
  - run tests
  - deploy to PyPI

jobs:
  include:
  - stage: run tests
    python: 2.7
    env: TOXENV=py27
  - python: 2.7
    env: TOXENV=py27-functional
  - python: 2.7
    env: TOXENV=update-pycodestyle
  - python: 3.7
    env: TOXENV=docs
  - python: 2.7
    env: TOXENV=coverage,codecov
  - python: 3.5
    env: TOXENV=py35
  - python: 3.5
    env: TOXENV=py35-functional
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=py36-functional
  - python: 3.7
    env: TOXENV=py37
  - python: 3.7
    env: TOXENV=py37-functional
  - python: 3.8
    env: TOXENV=py38
  - python: 3.8
    env: TOXENV=py38-functional
  - stage: deploy to PyPI
    deploy:
      provider: pypi
      user: __token__
      password:
        secure: gY5Rixj7mWHC9XP5qV5DfWGdX4ZVwCEUElnQA2OeIg235I3eMBqRFM4Q/SKwAG2DzgIWNKsXXVQsZHp7BAjWFMFVQloiU7zohuBRToJUim9U1RaqAjUIr4OU7JPtXenAl5zyyBdywvJiG8UZ4wmt1DBYtdpozQvOwDXvOxNTmElKh5mfDhiSsipmFr2198NtIhiRVC+CZliZsi6osUkt+G6yl9CW+SJU3otgzdaS+VBP26HO0kWHMJiDKvQoIl/Q50IqJUWieFhCLh7lSV71VNVEmM4bMcYK8cAv3zMZHo6REKHF7xrF5tzYMXqpmEGt6L798d2H4BISr6BIlYgiYCatjyE9hxih9iBzGs0XaGUUFD8u1iuzOQI76a5dapG/DixQrGD2o9Gn/Qw6Zp9USIuKZSWUn5hSobwxJUKVNy+afpaJNQUb2W9Hj+jMXAnBDodCzo3nu+QF8GN72cmk3uqVyKUVABtI4kNe3qcEx3DyKfoh7aqJrgydeaRwESKuZ41l5CA+vqXSbbNW8z1MYDYgVdwEyRFsLg6aQk5pPsxuiILaaGy13TUndhuC+GuKcW6wCDf6WpUAwwGAF8+sz4hZ1pfSUdE3F8nfDBW3Bv+G9cB/cKkWJ2vOd9httRrvir8qUc/xPP5aW4pacnfNCQ04Iep/k4PCAdYJDtVGhCY=
      skip_existing: true
      on:
        tags: true
        repo: kubernetes-client/python
      distributions: sdist bdist_wheel

install:
- pip install tox

script:
- tox

deploy:
  provider: pypi
  user: __token__
  password:
    secure: i2MuG6UQkOaH8SVPyRrM3SSWaanVKYHQ8omuTX1PMYQ9WF1xXYnA05K+bHjF1A2YFuXiQPTyE7OBjS5K07oWmhiwI1TYqKV9uAlkhrwxtmYl78efw7gpnKtFyhBcmlT0+wDo349HjyEnIhfvNrHxzzuSpP1oIXzmHokmgzxJzokpnQIYJcJppBcp4w/+RBUZdCvSf05gPQdYdzpLVvhJSKWaj3a1MXJbvz7f4sDfjyzUWGBDvg6lEM9WjlFeiu2KLM1h5FYgrpVBG+Ytl/WeyRRcIKfghqbyJ2sHHDqa7zftfgM/PkQgdWGARfe5V+kb66Xxptj3hrbILKMJ/kiUTQEOS6XGcnOd8purOfKJCX42aUHFUoJIUQk0thNX/y4mJEU1v/LQjBQR/WQnZNjANMnj/Mc7ORfF2a8eRPyop+sZ808MLlprZIeuNp4kM3q6tWxtfPREWfSMwSj+en7MEsU8hdogBch1A7Chm/BPckNKaYRuGvXYKmlr+EfezvdmvurT84hIlAjdVFGcmshv8f9ECp479nPDcH3vaRrt8kqqUzERB4ebGVPviC8qwjX+/R9xfBJeFs4Zo1VTOSsTmG9yJZk/PPbef6F1awLgBZnFIrmi5BZV8fDC78helDMOZTPDy+MLvA8wfxF5cQfz6q4LkFLkRVzvJC5/WcrILIc=
  skip_existing: true
  on:
    tags: true
    repo: palnabarun/python
  distributions: sdist bdist_wheel
