language: python
dist: xenial
services:
- docker
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 2.7
    env: TOXENV=py27-functional
  - python: 2.7
    env: TOXENV=update-pycodestyle
  - python: 3.7
    env: TOXENV=docs
  - python: 2.7
    env: TOXENV=coverage,codecov
  - python: 3.5
    env: TOXENV=py35
  - python: 3.5
    env: TOXENV=py35-functional
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=py36-functional
  - python: 3.7
    env: TOXENV=py37
  - python: 3.7
    env: TOXENV=py37-functional
  - python: 3.8
    env: TOXENV=py38
  - python: 3.8
    env: TOXENV=py38-functional
install:
- pip install tox
script:
- tox
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: i2MuG6UQkOaH8SVPyRrM3SSWaanVKYHQ8omuTX1PMYQ9WF1xXYnA05K+bHjF1A2YFuXiQPTyE7OBjS5K07oWmhiwI1TYqKV9uAlkhrwxtmYl78efw7gpnKtFyhBcmlT0+wDo349HjyEnIhfvNrHxzzuSpP1oIXzmHokmgzxJzokpnQIYJcJppBcp4w/+RBUZdCvSf05gPQdYdzpLVvhJSKWaj3a1MXJbvz7f4sDfjyzUWGBDvg6lEM9WjlFeiu2KLM1h5FYgrpVBG+Ytl/WeyRRcIKfghqbyJ2sHHDqa7zftfgM/PkQgdWGARfe5V+kb66Xxptj3hrbILKMJ/kiUTQEOS6XGcnOd8purOfKJCX42aUHFUoJIUQk0thNX/y4mJEU1v/LQjBQR/WQnZNjANMnj/Mc7ORfF2a8eRPyop+sZ808MLlprZIeuNp4kM3q6tWxtfPREWfSMwSj+en7MEsU8hdogBch1A7Chm/BPckNKaYRuGvXYKmlr+EfezvdmvurT84hIlAjdVFGcmshv8f9ECp479nPDcH3vaRrt8kqqUzERB4ebGVPviC8qwjX+/R9xfBJeFs4Zo1VTOSsTmG9yJZk/PPbef6F1awLgBZnFIrmi5BZV8fDC78helDMOZTPDy+MLvA8wfxF5cQfz6q4LkFLkRVzvJC5/WcrILIc=
  on:
    tags: true
    python: 3.7
  distributions: sdist bdist_wheel
